#' Render package citations
#'
#' @param Rmd.file Path to Rmarkdown file generated by [create_rmd()].
#' @param out.format Output format, either "html", docx" (Word), "pdf", or "md" (markdown).
#' @param out.dir Directory to save the output document. Default is the working directory.
#'
#' @return A document in the format specified by `out.format`.
#'
#' @noRd
#'

render_citations <- function(Rmd.file,
                             out.format = "html",
                             out.dir = getwd(),
                             out.name = "grateful-citations") {

  if (out.format == "docx") output <- "word_document"
  if (out.format == "pdf") output <- "pdf_document"
  if (out.format == "html") output <- "html_document"
  if (out.format == "md") output <- "md_document"

  rmarkdown::render(
    input = Rmd.file,
    output_format = output,
    output_file = paste0(out.name, ".", out.format),
    output_dir = out.dir
  )

}
